name: Deploy HTML to EC2

on:
  push:
    branches:
      - main  # This runs the workflow when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy index.html to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # The scp command copies your index.html file to the EC2 instance.
          # The -o StrictHostKeyChecking=no option bypasses the host key check,
          # which is simpler for this kind of automated deployment.
          scp -o StrictHostKeyChecking=no ./index.html ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:/var/www/html/

          echo "Deployment successful!"